name: transfer
channels:
  - defaults
dependencies:
  - pandas
  - lightgbm
  - tensorflow>=2.7
  - scikit-learn
  - python=3.9
  - numpy
  - keras
  - pip
  - pip:
    - git+https://github.com/jpgard/scikeras.git@5874f2fa3be5db6bcb44d674214fbfc9f6d62936
    - dill

